package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.33

import (
	"context"
	"scylladb/bookData"
	"scylladb/graph/model"
)

// CreateBookListing is the resolver for the createBookListing field.
func (r *mutationResolver) CreateBookListing(ctx context.Context, input model.CreateBookListingInput) (*model.BookListing, error) {
	createdBook, err := bookData.CreateBook(ctx, input)
	if err != nil {
		return nil, err
	}
	return createdBook, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
