// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BookListing struct {
	ID          string `json:"_id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Author      string `json:"author"`
}

type CreateBookListingInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Author      string `json:"author"`
}
